from __future__ import annotations

from typing import Any, Dict


class Callback:
    def on_run_start(self, cfg: Any, state: dict, model: Any) -> None: ...
    def on_epoch_start(self, cfg: Any, state: dict) -> None: ...
    def on_step_end(self, cfg: Any, state: dict, metrics: Dict[str, float]) -> None: ...
    def on_epoch_end(
        self, cfg: Any, state: dict, metrics: Dict[str, float]
    ) -> None: ...
    def on_checkpoint_saved(self, cfg: Any, state: dict, path: str) -> None: ...
    def on_run_end(self, cfg: Any, state: dict) -> None: ...
