name: multiblock

target_ratio: 0.25
context_ratio: 0.75
num_target_blocks: 1
allow_overlap: false
min_keep: 10

ctx_scale:  [0.85, 1.00]
ctx_aspect: [0.75, 1.50]

tgt_scale:  [0.60, 0.80]
tgt_aspect: [0.75, 1.50]
